version: '3.3'

volumes:
  postgres_data:
  static:

services:
  db:
    image: postgres:12.4
    volumes: 
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER

  nginx:
    # build: nginx/
    image: mariamozgunova/custom-nginx:latest
    volumes:
      - static:${STATIC_DIR}/static/
    environment:
      - HOST
    

  web:
    # build: .
    container_name: "yamdb-web-final"
    depends_on:
      - db
      - nginx
    environment:
      - DB_ENGINE
      - DB_HOST
      - DB_NAME
      - DB_PORT
      - DEBUG
      - HOST
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - SECRET_KEY
    image: mariamozgunova/yamdb-final:latest
    restart: always
