version: '3.3'

volumes:
  postgres_data:
  static:
  media:

services:
  db:
    image: postgres:12.4
    volumes: 
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER

  nginx:
    image: nginx:1.19.6-alpine
    volumes:
      # - static:${ROOT}/static/
      - media:${ROOT}/media/
      - ./nginx/static:${ROOT}/static
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    environment:
      - DOMAIN
      - HOST
      - WWWDOMAIN
    

  web:
    build: .
    container_name: yamdb-web
    depends_on:
      - db
      - nginx
    image: mariamozgunova/yamdb-final:latest
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DB_ENGINE
      - DB_HOST
      - DB_NAME
      - DB_PORT
      - DEBUG
      - DOMAIN
      - HOST
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - SECRET_KEY
      - WWWDOMAIN