version: '3.3'


volumes:
  media:
  postgres_data:
  static:


services:
  db:
    image: postgres:12.4
    volumes: 
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER

  web:
    container_name: yamdb-web
    depends_on:
      - db
    image: mariamozgunova/yamdb-final:latest
    restart: always
    environment:
      - DB_ENGINE
      - DB_HOST
      - DB_NAME
      - DB_PORT
      - DEBUG
      - DOMAIN
      - HOST
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - SECRET_KEY
      - WWWDOMAIN    
    volumes:
      - static:/code/static
      - media:/code/media

  nginx:
    depends_on:
        - web
    environment:
      - DOMAIN
      - HOST
      - WWWDOMAIN
    image: nginx:1.19.6-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - media:${ROOT}/media
      - static:${ROOT}/static
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf