version: '3.3'

volumes:
  postgres_data:
  static:

services:
  db:
    image: postgres:12.4
    volumes: 
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  nginx:
    build: nginx/
    ports:
      - "${HOST_IP}:80:80"
    volumes: 
      - static:/static/
    env_file:
      - ./.env
    

  web:
    build: .
    restart: always
    ports:
      - "${HOST_IP}:8000:8000"
    depends_on:
      - db
      - nginx
    env_file:
      - ./.env
