version: '3.3'


volumes:
  media:
  postgres_data:
  static:


services:
  certbot:
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot

  db:
    image: postgres:12.4
    volumes: 
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER

  nginx:
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    container_name: ${NGINX_CONTAINER}
    environment:
      - DJANGO_CONTAINER
      - DOMAIN
      - HOST
      - WWWDOMAIN
    image: nginx:1.19.6-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - media:${ROOT}/media
      - static:${ROOT}/static

  web:
    container_name: ${DJANGO_CONTAINER}
    depends_on:
      - db
    image: mariamozgunova/yamdb-final:latest
    restart: always
    environment:
      - DB_ENGINE
      - DJANGO_CONTAINER
      - DB_HOST
      - DB_NAME
      - DB_PORT
      - DEBUG
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - SECRET_KEY  
    volumes:
      - static:/code/static
      - media:/code/media