name: workflow


on: [push]


jobs: 
  tests:
    runs-on:  ubuntu-latest
    steps:  
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          pip install -r requirements.txt
      - name: Lint with flake8
        run: flake8 --exclude migrations,tests .
      - name: Test with pytest
        run: pytest 


  build_and_push_to_docker_hub:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push web to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: mariamozgunova/yamdb-final:latest
          # build-args: |
          #   DB_ENGINE=${{ secrets.DB_ENGINE }}
          #   DB_HOST=${{ secrets.DB_HOST }}
          #   DB_NAME=${{ secrets.DB_NAME }}
          #   DB_PORT=${{ secrets.DB_PORT }}
          #   DEBUG=${{ secrets.DEBUG }}
          #   DOMAIN=${{ secrets.DOMAIN }}
          #   HOST=${{ secrets.HOST }}
          #   POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
          #   POSTGRES_USER=${{ secrets.POSTGRES_USER }}
          #   SECRET_KEY=${{ secrets.SECRET_KEY }}
          #   WWWDOMAIN=${{ secrets.WWWDOMAIN }}


  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push_to_docker_hub
    steps:
    - uses: actions/checkout@v2
    - name: Copy docker-compose.yaml to server via SSH
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.SSH_KEY }}
        source: "docker-compose.yaml,nginx/nginx.conf,.env,redoc.yaml"
        target: "yamdb"
    - name: Execute remote ssh commands to deploy yamdb service
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.SSH_KEY }}
        passphrase: ${{ secrets.PASSPHRASE }}
        script: |
          cd yamdb
          sudo docker-compose down
          sudo docker-compose pull
          sudo docker-compose up -d
          sudo docker exec yamdb-web python manage.py makemigrations
          sudo docker exec yamdb-web python manage.py migrate
          sudo docker exec yamdb-web cp redoc.yaml static/redoc.yaml
    # - name: Deploy to Docker Host
    #   uses: wshihadeh/docker-deployment-action@v1
    #   with:
    #     remote_docker_host: admin@178.154.235.5
    #     ssh_private_key: ${{ secrets.RSA_PRIVATE_KEY }}
    #     ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }}
    #     copy_stack_file: 'true'
    #     deploy_path: '~/yamdb'
    #     keep_files: 100
    #     deployment_mode: docker-compose
    #     # pre_deployment_command_args: 'build'
    #     args: up -d
    #     docker_prune: 'false'
    # - name: Run a multi-line script
    #   run: |
    #     mkdir ../yamdb
    #     cp -TR . ../yamdb
    #     tar -cvf yamdb.tar ../yamdb/
    # - name: Setup SSH
    #   uses: kielabokkie/ssh-key-and-known-hosts-action@v1
    #   with:
    #     ssh-private-key: ${{ secrets.SSH_KEY }}
    #     ssh-host: ${{ secrets.USER }}@${{ secrets.HOST }}
    # - name: Run docker-compose
    #   uses: sudo-bot/action-docker-compose@latest
    #   with:
    #       cli-args: "build"
    # - name: Run docker-compose
    #   uses: sudo-bot/action-docker-compose@latest
    #   with:
    #       cli-args: "up -d"
        # pull_images_first: 'true'
    # - uses: isbang/compose-action@v0.1
    #   with:
    #     compose-file: 'docker-compose.yaml'


  notify:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
    - name: Send telegram message
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: ${{ github.workflow }} executed successfully! 

    - name: Send slack message
      uses: joshmgross/send-slack-message@main
      with: 
        channel: ${{ secrets.SLACK_TO }}
        slack-token: ${{ secrets.SLACK_TOKEN }}
        message: Just want to tell that your ${{ github.workflow }} terminated safely. 
